### ISSUE TITLE
Third-Party Build fails to due C++14 standard support is required to build.

### ISSUE THREAD

**Issue by markusstephanides** [pr0g/sdl-bgfx-imgui-starter#13]
![image](https://user-images.githubusercontent.com/6057570/174406330-21010c3d-1f5c-42ae-bfbf-c9823a034bce.png)

Unfortunately this is the error I now get when compiling using VS 2022 as generator.

**Comment by hultonha** [comment]
Argh yeah I spotted this too late sorry, you can fix this by going to the bgfx.cmake repo and adding `target_compile_features(dear-imgui PUBLIC cxx_std_14)` to the dear-imgui.cmake file.

The other simpler option might be to revert the very last commit in the starter repo for now.

I updated bgfx and the cmake wrapper has not been properly updated yet 😖 For some reason the dear-imgui library pulls in the bx source and tries to compile those files which it shouldn't...

I'm away for a week now sorry but will fix this properly when I'm back (likely 26th/27th)

**Comment by pr0g** [comment]
Fixed by 1057bd5d15e6ff6136d6e089e9670949cbfbd4d3 (please see https://github.com/pr0g/bgfx.cmake/commit/26a0f1e54d131841dab511539ff3e6c5e6472fed for details).

The crux was needing this compiler flag set for MSVC (`/Zc:__cplusplus`) due to a change in the `bx` library `bgfx` depends on.
