### ISSUE TITLE
Could not find SDL2Config.cmake, sdl2-config.cmake

### ISSUE THREAD

**Issue by ientos** [pr0g/sdl-bgfx-imgui-starter#2]
I get a CMake error when using "cmake -S . -B build":

CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "C:/dev/sdl-bgfx-imgui-starter/build/CMakeFiles/CMakeOutput.log".

It might only be my system, but shouldn't 'cmake -S . -B build" work without any further configuration from my part?

**Comment by pr0g** [comment]
Hey @ientos,

Looks like you got this working, you might have just missed the third-party step?

Cheers,


Tom
