### ISSUE TITLE
for android,ios, shaderc and bin2c 

### ISSUE THREAD

**Issue by mumin1616** [pr0g/sdl-bgfx-imgui-starter#20]
for android and ios,  what is  shaderc cmd line?
how entegration bin2c into that cmd line?
thanks.

**Comment by mumin1616** [comment]
after bgfx::init(init)),i checked es version:
it is opengl es 3.1 , okey.

i compiled simple shaders :

./shaderc -f v_simple.sc -o ./shader/android/v_simple.bin --platform android -p 300_es --type vertex --verbose -i ./
./shaderc -f f_simple.sc -o ./shader/android/f_simple.bin --platform android -p 300_es --type fragment --verbose -i ./

./bin2c -f ./shader/android/v_simple.bin -o ./header/android/v_simple.h -n vert_str
./bin2c -f ./shader/android/f_simple.bin -o ./header/android/f_simple.h -n frag_str

but i have errors:
ERROR: 0:9: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:10: 'out' : storage qualifier supported in GLSL ES 3.00 and above only

what is problem? compile line?

**Comment by pr0g** [comment]
Hi @mumin1616,

Good question, I took the commands you shared and updated them slightly to work more closely with the project layout and things seemed to work okay for me (this is on the latest version of the repo with `bgfx` at commit `bde3f94ce75ffd184e9a3bdfe947a3bec69233eb`).

```bash
./third-party/build/bin/shaderc -f shader/v_simple.sc -o shader/build/v_simple.bin --platform android --type vertex --verbose -i ./ -p 300_es
./third-party/build/bin/shaderc -f shader/f_simple.sc -o shader/build/f_simple.bin --platform android --type fragment --verbose -i ./ -p 300_es

./third-party/build/bin/bin2c -f shader/build/v_simple.bin -o shader/build/v_simple.h -n vert_str
./third-party/build/bin/bin2c -f shader/build/f_simple.bin -o shader/build/f_simple.h -n frag_str
```

I have to say I haven't tested Android with this project so it might be worth asking about this on the main https://github.com/bkaradzic/bgfx repo if you're still stuck.

I hope that helps a little, best of luck getting things working.

**Comment by pr0g** [comment]
Any luck testing this @mumin1616? Is this issue now resolved? If I don't hear back I'll close this issue in the next few days. Thanks.

**Comment by mumin1616** [comment]
i did it. no problem. thanks
