### ISSUE TITLE
after bgfx's new build , it is ugly font and antialliasing problem.

### ISSUE THREAD

**Issue by mumin16osx** [pr0g/sdl-bgfx-imgui-starter#21]
![Screenshot 2023-12-07 at 22 33 01](https://github.com/pr0g/sdl-bgfx-imgui-starter/assets/132001007/3e8ad1bd-c764-4f02-af39-a99fa1355863)

it is same in android , ios

**Comment by mumin16osx** [comment]
it is crash in linux and windows.

**Comment by pr0g** [comment]
Hi @mumin16osx, I'm not sure I fully understand the problem sorry and this doesn't look related to this repo directly, maybe it's worth asking in the [bgfx](https://github.com/bkaradzic/bgfx) main repo instead?

As a first glance it looks like the texture atlas for ImGui isn't being found for some reason, it might be that https://github.com/pr0g/sdl-bgfx-imgui-starter/blob/main/bgfx-imgui/fs_ocornut_imgui.bin.h and https://github.com/pr0g/sdl-bgfx-imgui-starter/blob/main/bgfx-imgui/vs_ocornut_imgui.bin.h need to be regenerated with a later version of bgfx if you're not using the same version from this repo (this is quite a convoluted process unfortunately, but I think I have it written down somewhere, if you think it's that I can try and share it).

Thanks!

**Comment by mumin16osx** [comment]
![screen](https://github.com/pr0g/sdl-bgfx-imgui-starter/assets/132001007/74da8bb3-0556-4d4f-8711-15ce08b78aae)

thanks mate! it's work. i updated fs_ocornut_imgui.bin.h and vs ocornut imgui.bin.h from main repo.

**Comment by pr0g** [comment]
No problem! That's great to hear 🥳 Thanks for confirming, are you happy if I close the issue now?

**Comment by mumin1616** [comment]
ok...
