### ISSUE TITLE
Full screen have multiple issues

### ISSUE THREAD

**Issue by ernesernesto** [pr0g/sdl-bgfx-imgui-starter#22]
Creating a full screen SDL_Window with flag SDL_WINDOW_FULLSCREEN_DESKTOP has multiple issues, see attached screenshot.

<img width="938" alt="fullscreen" src="https://github.com/pr0g/sdl-bgfx-imgui-starter/assets/3048906/c43bb42d-6050-4853-8a3a-5500962aeb5c">
Font looks blurry

<img width="960" alt="fullscreen_clipped" src="https://github.com/pr0g/sdl-bgfx-imgui-starter/assets/3048906/516555a7-2fe7-4111-968a-43700471deac">
Demo window got clipped when moved into a different position than the default one

**Comment by pr0g** [comment]
Hey @ernesernesto,

Ah the most likely reason for this is the app doesn't handle the `SDL_WINDOWEVENT_RESIZED` or `SDL_WINDOWEVENT_SIZE_CHANGED` events in the main event loop (line 70). Adding this shouldn't be too hard, I have done this in another project, I think you just need to add something like...

```
bgfx::reset(context->width, context->height);
bgfx::setViewRect(0, 0, 0, context->width, context->height);
```

For those events, e.g.

```
case SDL_WINDOWEVENT_RESIZED:
case SDL_WINDOWEVENT_SIZE_CHANGED: {
  // above code...
} break;
```

I am afraid don't have time to look at this now, but give that a try, and if you'd like to open a PR please feel free 🙂

**Comment by ernesernesto** [comment]
Hi @pr0g the problem still exists even after adding
```c++
     for (SDL_Event current_event; SDL_PollEvent(&current_event) != 0;) {
        ImGui_ImplSDL2_ProcessEvent(&current_event);
        switch (current_event.type) {
            case SDL_QUIT: {
                context->quit = true;
                break;
            }
            case SDL_WINDOWEVENT_RESIZED:
            case SDL_WINDOWEVENT_SIZE_CHANGED: {
                bgfx::reset(context->width, context->height);
                bgfx::setViewRect(0, 0, 0, context->width, context->height);
                break;
            }
        }
    }
```

**Comment by pr0g** [comment]
Hmm have you added a breakpoint (or `printf` 😅) just to check that code is called on start?

You might have to call `SDL_GetWindowSize` at the start (at the beginning of the `main` function after `SDL_CreateWindow`) to get the new width/height of the window, and pass that through instead of using the hardcoded 800/600 values.

**Comment by ernesernesto** [comment]
Sorry, that was a bit of a brain fart, I was handling incorrect window sdl events, here are the correct one with those issue fixed

```c
    for (SDL_Event current_event; SDL_PollEvent(&current_event) != 0;) {
        ImGui_ImplSDL2_ProcessEvent(&current_event);
        switch (current_event.type) {
            case SDL_QUIT: {
                context->quit = true;
                break;
            }
            case SDL_WINDOWEVENT: {
                switch (current_event.window.event) {
                    case SDL_WINDOWEVENT_RESIZED:
                    case SDL_WINDOWEVENT_SIZE_CHANGED: {
                        bgfx::reset(
                            current_event.window.data1,
                            current_event.window.data2);
                        bgfx::setViewRect(
                            0, 0, 0, current_event.window.data1,
                            current_event.window.data2);
                        break;
                    } break;
                }
            }
        }
    }


```

**Comment by pr0g** [comment]
No worries at all, sorry I missed off the `SDL_WINDOWEVENT` in my initial answer.

Glad you got it working, if you fancy opening a PR with the functionality feel free, I might see if I can update it in the not too distant future.
