### ISSUE TITLE
Build not working on windows

### ISSUE THREAD

**Issue by markusstephanides** [pr0g/sdl-bgfx-imgui-starter#3]
Hi, thanks for your work, really helpful for bgfx starters!

I followed the instructions in https://github.com/pr0g/sdl-bgfx-imgui-starter/blob/main/third-party/README.md and everything ran through successfully. Got everything working until the actual build process. configure.bat runs successfully but the build doesn't. These are the errors:

![image](https://user-images.githubusercontent.com/6057570/116083594-122dcd80-a69d-11eb-8ff8-8a055e8627ad.png)

Would appreciate any hints!

**Comment by pr0g** [comment]
Hey @markusstephanides,

I'll try reproduce this later but my guess is it could be to do with the config (debug or release mismatch). You might need to also build the third party libraries in debug (or release) too depending on which you already did, you can do this by using `--config` if using visual studio with the build command or use `-DCMAKE_BUILD_TYPE=Release` if using Ninja.

Let me know if that helps,

Cheers,

Tom

**Comment by markusstephanides** [comment]
Didn't change anything unfortunately, also if it helps, it seems like CLion doesn't find some of the includes I'm using CMake 3.15.4

**Comment by pr0g** [comment]
Ah okay, I haven't tested with Clion on Windows but I have a licence so will try take a look later today or tomorrow at the latest.

If you're using Clion it'll be to do with the `-DCMAKE_BUILD_TYPE` variable. I'd see if you can get it working just using command line if you can to see if you can isolate the problem.

Thanks,

Tom

**Comment by markusstephanides** [comment]
I did everything in cmd/git bash, only after I saw that it doesn't work, I opened CLion to see if I can get further information.

**Comment by pr0g** [comment]
I just tested this locally and it seemed to work okay. I cloned the repo and navigated to the `third-party` folder and ran..

```bash
cmake -S . -B build
cmake --build build\ --config Debug
```
_(this was using the Visual Studio generator)_

Then went back to the root and ran `configure.bat` followed by ` cmake --build build\debug\` and it worked (I also had to run `.\compile-shaders-win.bat` for things to run).

Can you give those steps a try again?

Thanks,

Tom

**Comment by markusstephanides** [comment]
Did exactly the same steps you described (I omitted the backflash from cmake --build build\ --config Debug because it gave me an error, still took the correct directory) and I have the same results :/ 

Maybe if it helps the outputs of the commands:

![image](https://user-images.githubusercontent.com/6057570/116103987-61312e00-a6b0-11eb-904f-bcda8b8de6b4.png)

![image](https://user-images.githubusercontent.com/6057570/116104050-6e4e1d00-a6b0-11eb-84c1-0e8131bd2cb6.png)

![image](https://user-images.githubusercontent.com/6057570/116104135-7efe9300-a6b0-11eb-9e1d-adf58193b006.png)

**Comment by pr0g** [comment]
Oh interesting it looks like a different compiler gets picked when you run the `configure.bat` file 😬 

Can you delete the build folder in the root again and run this...

```
cmake -S . -B build -DCMAKE_PREFIX_PATH=%cd%/third-party/build
cmake --build build --config Debug
```

That should wind up picking Visual Studio again and I think _should_ work

**Comment by markusstephanides** [comment]
Awesome, that works thank you very much! :)

Have a great evening!

**Comment by pr0g** [comment]
Awesome! 😄 If you wanted to to use GNU instead you'd need to use that when building the third party libraries too (you could use Ninja in the third-party step).

Anyway glad it's working, thanks for letting me know 👍
