### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zhangfq-chemistry** [pr0g/sdl-bgfx-imgui-starter#4]
zhangfq@zhangfq-Precision-3640-Tower:~/zhangfq/sdl-bgfx-imgui-starter$ ./configure.sh
-- Configuring done
CMake Error at CMakeLists.txt:9 (add_executable):
  Target "sdl-bgfx-imgui-starter" links to target "imgui::imgui" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by pr0g** [comment]
Hey @zhangfq-chemistry 

It looks like you might not have done the third party step yet, can you try that please or confirm if you have.

Thanks,

Tom

**Comment by zhangfq-chemistry** [comment]
I follow README.md under sdl-bgfx-imgui-starter/third-party without errors
sudo apt-get install libx11-dev libglu1-mesa-dev libgl1-mesa-glx libxext-dev ninja-build
cd third-party
cmake -S . -B build
cmake --build build

After that, the configure.sh still wrong: 
zhangfq@zhangfq-Precision-3640-Tower:~/zhangfq/sdl-bgfx-imgui-starter$ ./configure.sh
-- Configuring done
CMake Error at CMakeLists.txt:9 (add_executable):
  Target "sdl-bgfx-imgui-starter" links to target "imgui::imgui" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by pr0g** [comment]
Hmm okay, so the `third-party/CMakeLists.txt` is correct as `cmakefied` is the wrapper that brings in `imgui`. It's possible that `imgui` has changed recently and is no longer building, which is causing the target to not be found when running the main `configure.sh` script.

Can you confirm what platform/OS you're on please? I'll see if I can repro locally.

Cheers!

Tom

**Comment by pr0g** [comment]
The other issue could be the fact Ninja is used in the `configure.sh` command for the main build but we're using Make files (or something else) when building the third-party dependencies. When building the third-party dependencies you could try using Ninja as the generator too (pass `-G Ninja` when configuring) or use whatever the native generator is for the main build (if you copy the command that's in `configure.sh` but just omit the `-G Ninja` bit you could give that a try (I'm just building atm to see if I can see the same issue, I'm testing on Ubuntu).

**Comment by pr0g** [comment]
I was able to build and run from scratch locally and everything seemed to work okay, can you check if you have these files in your `third-party/build` folder

```
lib/cmake/imgui/imgui-config-debug.cmake
lib/cmake/imgui/imgui-config.cmake
```

**Comment by zhangfq-chemistry** [comment]
I use ubunutu
(1) "configure.sh  -G Ninja " still does not work (2) I have the two files as you see : zhangfq@zhangfq-Precision-3640-Tower:~/bgfx2/sdl-bgfx-imgui-starter/third-party/lib/cmake/imgui$ ls
imgui-config.cmake  imgui-config-debug.cmake

**Comment by pr0g** [comment]
Oh no sorry that won't work, I mean modify the command inside configure.sh (remove the -G Ninja bit)

**Comment by pr0g** [comment]
You can see inside there what the full command is doing, the important bit is -DCMAKE_PREFIX_PATH which is where we're telling CMake where to look for the installed libraries

**Comment by zhangfq-chemistry** [comment]
Would you like to send message from your email to zhangfq@sxnu.edu.cn, and then I can provided my ip and passwd to you. Thanks!

**Comment by pr0g** [comment]
That won't be necessary, can you try this as one last step... I'm going to list all the commands you need individually, if you can sync the repo again and try this from scratch it will hopefully get things working. If not can you please attach as much log info as possible (I'd like to know if building the third-party dependencies is failing).

```
mkdir sdl-bgfx-imgui-starter && cd sdl-bgfx-imgui-starter
git clone https://github.com/pr0g/sdl-bgfx-imgui-starter.git .
cd third-party
cmake -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build
cd ..
cmake -B build/debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="$(pwd)/third-party/build"
cmake --build build/debug
```

That should _hopefully_ work - can you give that a try and let me know what errors you hit (ideally when you build third-party and when building the project).

**Comment by pr0g** [comment]
@zhangfq-chemistry Were you able to have any luck with the steps above? I'm going to close this issue in the next 24hrs or so if there's no update. Thanks.
