### ISSUE TITLE
Font display incorrectly for DearImgui?

### ISSUE THREAD

**Issue by Trung0246** [pr0g/sdl-bgfx-imgui-starter#5]
Hi, after attempting to compile the code (I have to recompile the shader v_simple.sc and f_simple.sc using latest shaderc.exe from bgfx due to the fact that essl is missing, not sure if it's affected by that), the result is this:
![image](https://user-images.githubusercontent.com/11626920/123252542-3fcaa380-d4a1-11eb-9a87-39a1773e91a0.png)
DearImgui version is 1.83 (yes I tried to compile bgfx examples since they uses DearImgui too and font displayed correctly there so I think it's the issue with the sdl-bgfx-imgui-starter. I don't change anything in the main.cpp and bgfx-imgui and sdl-imgui beside the *.bin.h shader.

Here is the compiled result if you're wondering
[fs_ocornut_imgui.bin.txt](https://github.com/pr0g/sdl-bgfx-imgui-starter/files/6708662/fs_ocornut_imgui.bin.h.txt)
[vs_ocornut_imgui.bin.txt](https://github.com/pr0g/sdl-bgfx-imgui-starter/files/6708663/vs_ocornut_imgui.bin.h.txt)

**Comment by pr0g** [comment]
Hmm interesting, this looks familiar, I'm sure I got this too at some point while setting this up... 🤔 

Did you go through the setup in the `third-party` folder first? Also what is `essl` sorry? Also what changes did you make in the `*.bin.h` code? That is directly related to all the ImGui rendering so could _potentially_ be related? 😬 I'm not sure though...

**Comment by pr0g** [comment]
Could you also please let me know what platform you're on, cheers 👍

**Comment by pr0g** [comment]
Could be related to a blend state thing too if you have something doing that in your code https://github.com/ocornut/imgui/issues/1258

**Comment by pr0g** [comment]
There's also some info on what might be causing it here - https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-i-integrated-dear-imgui-in-my-engine-and-little-squares-are-showing-instead-of-text

**Comment by Trung0246** [comment]
![image](https://user-images.githubusercontent.com/11626920/123331147-c019f480-d4f3-11eb-83e1-56a3e017e24d.png)
Here is what its looks like when using the old *.bin.h

**Comment by pr0g** [comment]
Huh... Are you using the version of bgfx specified in the third party folder? Or from a different commit?

**Comment by Trung0246** [comment]
> Huh... Are you using the version of bgfx specified in the third party folder? Or from a different commit?

Yeah I'm using the version from the bgfx latest commit (version 7816, commit hash e642efb03af78e04bec8e81118fe3dec88e0176e), and SDL version 2.0.14

**Comment by pr0g** [comment]
Ah okay I see the problem, this repo is only tested up to commit `1971d7268bab35d09e9aa073634bb9c1ba9998e2`

It's intended to be used by running the steps in `third-party` - it looks like the version of `bgfx` you're using has had some breaking change. I'll try and update the repo to use the latest commit in the next few days (likely next week as I'm away this weekend). Can you try either running the steps in `third-party` or get `bgfx` at the commit listed above.

**Comment by Trung0246** [comment]
Ok I found the problem: apparently the compiled shader result from the old *.bin.h work fine if I just add a stub array that have nonsense data (like `static const uint8_t vs_ocornut_imgui_essl[1] = {0x0};`) and it works I guess?
![image](https://user-images.githubusercontent.com/11626920/123333772-06248780-d4f7-11eb-8b38-3809a997c9c8.png)
So it's looks like the compiled data from *.bin.h is different from f_simple.sc and v_simple.sc? Do you have access to the original shader code that compiled to those *.bin.h?

**Comment by pr0g** [comment]
It's because latest `bgfx` has regenerated those files (see the history here - https://github.com/bkaradzic/bgfx/commits/master/examples/common/imgui/vs_ocornut_imgui.bin.h) I just need to update this lib to use the latest `bgfx` commit and copy those files into this repo too - but that'll have to be next week 🙂 

Glad you got it working for now though 👍

**Comment by pr0g** [comment]
FYI `bgfx` and related Dear ImGui functionality has been updated to latest (see 1b08563d5e43ea877cf347a3ecb4698d6eb3d15f and 068dc2c9cbc2f6408bf8848698a87691b554e1b7). Cheers!
